In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
from scipy.linalg import solve_triangular
a = np.array([[3,0,0,0],
              [2,1,0,0],
              [1,0,1,0],
              [1,1,1,1]])
b = np.array([4,2,4,2])
x = solve_triangular(a,b,lower=True)
x

array([ 1.33333333, -0.66666667,  2.66666667, -1.33333333])

In [3]:
from scipy.linalg import solve_toeplitz,toeplitz
c = np.array([1,3,6,10])
r = np.array([1,-1,-2,-3])
b = np.array([1,2,2,5])
x = solve_toeplitz((c,r),b)
x

array([ 1.66666667, -1.        , -2.66666667,  2.33333333])

***Eigenvalue Problems***

In [4]:
from scipy.linalg import eigh_tridiagonal
d = 3*np.ones(4)
e = -1*np.ones(3)
w,v = eigh_tridiagonal(d,e)

In [5]:
w

array([1.38196601, 2.38196601, 3.61803399, 4.61803399])

In [6]:
v.T[0]

array([0.37174803, 0.60150096, 0.60150096, 0.37174803])

In [7]:
v.T[1]

array([ 0.60150096,  0.37174803, -0.37174803, -0.60150096])

### Special Matrices 

In [8]:
from scipy.linalg import fiedler
fiedler([1,4,12,45])

array([[ 0,  3, 11, 44],
       [ 3,  0,  8, 41],
       [11,  8,  0, 33],
       [44, 41, 33,  0]])

In [10]:
from scipy.linalg import toeplitz
toeplitz([1,2,3,6,0,0],[1,4,5,6,0,0])

array([[1, 4, 5, 6, 0, 0],
       [2, 1, 4, 5, 6, 0],
       [3, 2, 1, 4, 5, 6],
       [6, 3, 2, 1, 4, 5],
       [0, 6, 3, 2, 1, 4],
       [0, 0, 6, 3, 2, 1]])

## Decompositions

In [12]:
from scipy.linalg import lu
A = np.array([[2,5,7,8],[5,2,2,8],[7,5,6,6],[5,4,4,8]])
A

array([[2, 5, 7, 8],
       [5, 2, 2, 8],
       [7, 5, 6, 6],
       [5, 4, 4, 8]])

In [13]:
p, l, u = lu(A)

In [14]:
p

array([[0., 1., 0., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.]])

In [15]:
l

array([[ 1.        ,  0.        ,  0.        ,  0.        ],
       [ 0.28571429,  1.        ,  0.        ,  0.        ],
       [ 0.71428571,  0.12      ,  1.        ,  0.        ],
       [ 0.71428571, -0.44      , -0.04347826,  1.        ]])

In [16]:
u

array([[ 7.        ,  5.        ,  6.        ,  6.        ],
       [ 0.        ,  3.57142857,  5.28571429,  6.28571429],
       [ 0.        ,  0.        , -0.92      ,  2.96      ],
       [ 0.        ,  0.        ,  0.        ,  6.60869565]])